"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { ArrowUpRight, Menu, X } from "lucide-react";
import { profile } from "@/data/profile";
import { LanguageSwitcher } from "@/components/i18n/language-switcher";
import { ThemeToggle } from "@/components/home/felt-portfolio";
import { useDictionary } from "@/components/i18n/use-dictionary";
export function Header() { const pathname = usePathname(); const [open, setOpen] = useState(false); const { dictionary, locale } = useDictionary(); const links = pathname === "/" ? [{ href: "#approach", label: locale === "fr" ? "Approche" : "Approach" }, { href: "#work", label: dictionary.nav.work }, { href: "#about", label: dictionary.nav.about }, { href: "#contact", label: dictionary.nav.contact }] : [{ href: "/", label: dictionary.nav.home }, { href: "/projects", label: dictionary.nav.work }, { href: "/about", label: dictionary.nav.about }, { href: "/contact", label: dictionary.nav.contact }]; return <header className="felt-header"><div className="felt-container header-inner"><Link href="/" className="felt-wordmark" aria-label={`${profile.name}, ${dictionary.nav.home}`}><strong>at<span>.</span></strong><span>{profile.name}</span></Link><nav className="desktop-nav" aria-label="Main navigation">{links.map(({ href, label }) => <Link key={href} href={href}>{label}</Link>)}<a href={`mailto:${profile.email}`} className="header-email">{dictionary.nav.contact}<ArrowUpRight size={14} /></a><LanguageSwitcher /><ThemeToggle /></nav><button className="menu-toggle" aria-label={open ? "Close navigation" : "Open navigation"} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X size={22} /> : <Menu size={22} />}</button></div>{open && <nav className="mobile-nav felt-container" aria-label="Mobile navigation">{links.map(({ href, label }) => <Link key={href} href={href} onClick={() => setOpen(false)}>{label}<ArrowUpRight size={17} /></Link>)}<a href={`mailto:${profile.email}`}>Email<ArrowUpRight size={17} /></a><div className="mobile-controls"><LanguageSwitcher /><ThemeToggle /></div></nav>}</header>; }
